@startuml

'Diagramme de classes (PlantUML)'

'Configuration charte graphique'
hide empty methods
hide circle
skinparam class {
  BackgroundColor White
  ArrowColor Black
  BorderColor Black
}

'Classes, énumérations, etc.'
class MiniSocs {
  - nom: String
}

class Utilisateur {
  - pseudonyme: String
  - nom: String
  - prénom: String
  - courriel: String
  - etatCompte: ÉtatCompte
}
enum ÉtatCompte <<enum>> {
  ACTIF
  DÉSACTIVÉ
  BLOQUÉ
  DÉBLOQUÉ
}

class Participation {
  - pseudoParticulier: String
  - modérateur: Bool
  / pseudonyme: String
}

class ReseauSocial {
  - nom: String
}

class Message {
  - contenu: String
  - accepté: bool
  /pseudoParticulier: String
}

'Associations, etc.'
MiniSocs *--> "*" Utilisateur
Utilisateur "1" *-- "*" Participation: possède
Participation "*" --> "1" ReseauSocial: modère (si modérateur=True)
Participation "*" --> "1" ReseauSocial: appartient (si modérateur=False)
Participation "1" *--> "*" Message: Demander (si modérateur=False)
Participation "1" *--> "*" Message: Poster (si modérateur=True)
Message "*" <--* "1" ReseauSocial: contient
MiniSocs *--> "*" ReseauSocial

'Au besoin, aides pour le positionnement'

@enduml
