@startuml

'Diagramme de séquence (PlantUML)'

'Configuration charte graphique'
hide footbox
skinparam sequenceParticipantBackgroundColor White
skinparam sequenceActorBackgroundColor White

'Déclaration des acteurs et des participants (déjà existants avant la séquence)'
actor "__:Administrateur__" as admin
participant "__m:MiniSocs__" as m

'Séquence avec les messages, les créations de participants, etc.'
admin -> m ++ : creerReseauSocial(pseudoExec, nomReseau, ouvert, pseudoParticulier)
opt pseudoExec non null ∧ non vide
  m -> m ++ : u=chercherUtilisateur(pseudoExec): Utilisateur
  return
  opt u != null et u.getEtatCompte() == ACTIF
    opt nomReseau non null ∧ non vide
      m -> m ++ : rs=chercherReseauSocial(nomReseau): ReseauSocial
      return
      opt rs == null
        create "__rs:ReseauSocial__" as rs
        m -> "__rs:ReseauSocial__" as rs ++ : rs=<<create(nomReseau, ouvert)>>
        return
        m -> m ++ : ajouterMembreRS(pseudoExec, nomReseau, pseudoParticulier, true)
        return
      end
    end
  end
end
return

@enduml

