@startuml

' Configuration charte graphique
' États et transitions
skinparam state {
    FontSize 10
    RoundCorner 10
}

state EnCréation : entry : constructeur()
state EnDestruction : entry : destructeur()

[*] -right-> EnCréation
EnCréation --> VerificationPending: membre non modérateur / ajouterMessage()
EnCréation --> Sent: membre modérateur / ajouterMessage()

VerificationPending --> EnDestruction: Supprimé par mod / delete_message()
VerificationPending --> Inappropriate: modifierStatutMessage(Inappropriate)
VerificationPending --> Hidden: modifierStatutMessage(Hidden)
VerificationPending --> Sent: modifierStatutMessage(Sent)

Hidden              --> EnDestruction: Supprimé par mod / delete_message()
Hidden              --> Inappropriate: modifierStatutMessage(Inappropriate)
Hidden              --> Sent: modifierStatutMessage(Sent)
Hidden              --> VerificationPending: modifierStatutMessage(VerificationPending)

Inappropriate       --> EnDestruction: Supprimé par mod / delete_message()
Inappropriate              --> Hidden: modifierStatutMessage(Hidden)
Inappropriate              --> Sent: modifierStatutMessage(Sent)
Inappropriate              --> VerificationPending: modifierStatutMessage(VerificationPending)

Sent --> EnDestruction: Supprimé par mod / delete_message()
Sent              --> Hidden: modifierStatutMessage(Hidden)
Sent              --> Inappropriate: modifierStatutMessage(Inappropriate)
Sent              --> VerificationPending: modifierStatutMessage(VerificationPending)

EnDestruction-left-> [*]

@enduml
